comment:
  layout: "header, diff, components"

component_management:
  individual_components:
    - component_id: mod-gi
      name: gi
      paths:
        - gi/**
    - component_id: mod-optional
      name: optional
      paths:
        - optional/**
